version: '3.8'
services:
  web:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    volumes:
      - ~/.aws/workdocs:/root/.aws/credentials:ro
    ports:
      - "3000:3000"
