version: '3'
services:
  web:
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && ./bin/dev"
    stdin_open: true
    volumes:
      - .:/myapp
      - ~/.aws/workdocs:/root/.aws/credentials:ro
    ports:
      - "3000:3000"
