version: '3.8'
services:
  web:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    volumes:
      - ~/.aws/workdocs:/root/.aws/credentials:ro
    environment:
      BASIC_AUTH_USERNAME: test
      BASIC_AUTH_PASSWORD: test
    ports:
      - "3000:3000"
